In [471]:
import numpy as np
import pandas as pd

In [472]:
df = pd.read_csv("C:/Users/tabis/Desktop/Laptop price prediction/dataset/Laptop_price.csv")

In [473]:
df.head()

Brand  Processor_Speed  RAM_Size  Storage_Capacity  Screen_Size    Weight  \
0    Asus         3.830296        16               512    11.185147  2.641094   
1    Acer         2.912833         4              1000    11.311372  3.260012   
2  Lenovo         3.241627         4               256    11.853023  2.029061   
3    Acer         3.806248        16               512    12.280360  4.573865   
4    Acer         3.268097        32              1000    14.990877  4.193472   

          Price  
0  17395.093065  
1  31607.605919  
2   9291.023542  
3  17436.728334  
4  32917.990718

In [474]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Brand             1000 non-null   object 
 1   Processor_Speed   1000 non-null   float64
 2   RAM_Size          1000 non-null   int64  
 3   Storage_Capacity  1000 non-null   int64  
 4   Screen_Size       1000 non-null   float64
 5   Weight            1000 non-null   float64
 6   Price             1000 non-null   float64
dtypes: float64(4), int64(2), object(1)
memory usage: 54.8+ KB


In [475]:
df.describe()

Processor_Speed     RAM_Size  Storage_Capacity  Screen_Size  \
count      1000.000000  1000.000000       1000.000000  1000.000000   
mean          2.750611    15.500000        584.576000    14.056790   
std           0.731796    10.988665        313.438517     1.705882   
min           1.511580     4.000000        256.000000    11.012111   
25%           2.089246     8.000000        256.000000    12.635523   
50%           2.760885    16.000000        512.000000    14.099643   
75%           3.362610    32.000000       1000.000000    15.528590   
max           3.998534    32.000000       1000.000000    16.985737   

            Weight         Price  
count  1000.000000   1000.000000  
mean      3.466919  19604.187963  
std       0.866541   9406.064880  
min       2.000560   8570.012950  
25%       2.717211  10114.012948  
50%       3.464630  17287.241878  
75%       4.212583  31566.214754  
max       4.990728  33503.935037

In [476]:
list_columns = pd.Series(df.columns).to_list()

In [477]:
list_columns

['Brand',
 'Processor_Speed',
 'RAM_Size',
 'Storage_Capacity',
 'Screen_Size',
 'Weight',
 'Price']

In [478]:
df['Brand'].unique()

array(['Asus', 'Acer', 'Lenovo', 'HP', 'Dell'], dtype=object)

In [479]:
df['RAM_Size'].unique()

array([16,  4, 32,  8], dtype=int64)

In [480]:
df['Storage_Capacity'].unique()

array([ 512, 1000,  256], dtype=int64)

In [481]:
df.describe()

Processor_Speed     RAM_Size  Storage_Capacity  Screen_Size  \
count      1000.000000  1000.000000       1000.000000  1000.000000   
mean          2.750611    15.500000        584.576000    14.056790   
std           0.731796    10.988665        313.438517     1.705882   
min           1.511580     4.000000        256.000000    11.012111   
25%           2.089246     8.000000        256.000000    12.635523   
50%           2.760885    16.000000        512.000000    14.099643   
75%           3.362610    32.000000       1000.000000    15.528590   
max           3.998534    32.000000       1000.000000    16.985737   

            Weight         Price  
count  1000.000000   1000.000000  
mean      3.466919  19604.187963  
std       0.866541   9406.064880  
min       2.000560   8570.012950  
25%       2.717211  10114.012948  
50%       3.464630  17287.241878  
75%       4.212583  31566.214754  
max       4.990728  33503.935037

In [482]:
import seaborn as sns

In [483]:
import plotly.express as px
import matplotlib.pyplot as plt

In [484]:
for i in list_columns:
    fig = px.scatter(data_frame=df, x = 'Price' , y = i, color = 'Brand')
    fig.show()

In [485]:
df.groupby(['Brand']).count()

Processor_Speed  RAM_Size  Storage_Capacity  Screen_Size  Weight  \
Brand                                                                      
Acer                204       204               204          204     204   
Asus                206       206               206          206     206   
Dell                210       210               210          210     210   
HP                  190       190               190          190     190   
Lenovo              190       190               190          190     190   

        Price  
Brand          
Acer      204  
Asus      206  
Dell      210  
HP        190  
Lenovo    190

In [486]:
list_columns

['Brand',
 'Processor_Speed',
 'RAM_Size',
 'Storage_Capacity',
 'Screen_Size',
 'Weight',
 'Price']

In [487]:
n = len(list_columns)
print(n)

7


In [488]:
for i in range(0, n):
    print(list_columns[i])
    for j in range(i+1, n):
        print("\t", list_columns[j])
        #print(i, j)
        #fig = px.scatter(data_frame=df, x = df[list_columns[i]] , y =df[list_columns[j]], color = 'Price')
        #fig.show()

Brand
	 Processor_Speed
	 RAM_Size
	 Storage_Capacity
	 Screen_Size
	 Weight
	 Price
Processor_Speed
	 RAM_Size
	 Storage_Capacity
	 Screen_Size
	 Weight
	 Price
RAM_Size
	 Storage_Capacity
	 Screen_Size
	 Weight
	 Price
Storage_Capacity
	 Screen_Size
	 Weight
	 Price
Screen_Size
	 Weight
	 Price
Weight
	 Price
Price


In [489]:
fig = px.scatter(data_frame=df, x = 'RAM_Size', y = 'Price', color = 'Brand')
fig.show()

In [490]:
fig = px.scatter(data_frame=df, x = 'Processor_Speed', y = 'Price', color = 'Brand')
fig.show()

In [491]:
fig = px.scatter(data_frame=df, x = 'Storage_Capacity', y = 'Price', color = 'Brand')
fig.show()

In [492]:
fig = px.scatter(data_frame=df, x = 'Weight', y = 'Price', color = 'Brand')
fig.show()

In [493]:
fig = px.scatter(data_frame=df, x = 'Screen_Size', y = 'Price', color = 'Brand')
fig.show()

In [494]:
df.head()

Brand  Processor_Speed  RAM_Size  Storage_Capacity  Screen_Size    Weight  \
0    Asus         3.830296        16               512    11.185147  2.641094   
1    Acer         2.912833         4              1000    11.311372  3.260012   
2  Lenovo         3.241627         4               256    11.853023  2.029061   
3    Acer         3.806248        16               512    12.280360  4.573865   
4    Acer         3.268097        32              1000    14.990877  4.193472   

          Price  
0  17395.093065  
1  31607.605919  
2   9291.023542  
3  17436.728334  
4  32917.990718

In [495]:
df['Brand'] = df['Brand'].astype('category')
df['RAM_Size'] = df['RAM_Size'].astype('category')
df['Storage_Capacity'] = df['Storage_Capacity'].astype('category')

In [496]:
df.head()

Brand  Processor_Speed RAM_Size Storage_Capacity  Screen_Size    Weight  \
0    Asus         3.830296       16              512    11.185147  2.641094   
1    Acer         2.912833        4             1000    11.311372  3.260012   
2  Lenovo         3.241627        4              256    11.853023  2.029061   
3    Acer         3.806248       16              512    12.280360  4.573865   
4    Acer         3.268097       32             1000    14.990877  4.193472   

          Price  
0  17395.093065  
1  31607.605919  
2   9291.023542  
3  17436.728334  
4  32917.990718

In [497]:
df['Brand_new'] = df['Brand'].cat.codes
df['RAM_Size_new'] = df['RAM_Size'].cat.codes
df['Storage_Capacity_new'] = df['Storage_Capacity'].cat.codes

In [498]:
df.head()

Brand  Processor_Speed RAM_Size Storage_Capacity  Screen_Size    Weight  \
0    Asus         3.830296       16              512    11.185147  2.641094   
1    Acer         2.912833        4             1000    11.311372  3.260012   
2  Lenovo         3.241627        4              256    11.853023  2.029061   
3    Acer         3.806248       16              512    12.280360  4.573865   
4    Acer         3.268097       32             1000    14.990877  4.193472   

          Price  Brand_new  RAM_Size_new  Storage_Capacity_new  
0  17395.093065          1             2                     1  
1  31607.605919          0             0                     2  
2   9291.023542          4             0                     0  
3  17436.728334          0             2                     1  
4  32917.990718          0             3                     2

In [499]:
from sklearn.preprocessing import OneHotEncoder

In [500]:
OHEencoder = OneHotEncoder(sparse=False)
Brand_dummies = OHEencoder.fit_transform(df[['Brand']])
Brand_dummies_df = pd.DataFrame(Brand_dummies, columns=sorted(df['Brand'].unique()))

In [501]:
RAM_Size_dummies = OHEencoder.fit_transform(df[['RAM_Size']])
RAM_Size_dummies_df = pd.DataFrame(RAM_Size_dummies, columns=[str(i) for i in sorted(df['RAM_Size'].unique())])

In [502]:
Storage_Capacity_dummies = OHEencoder.fit_transform(df[['Storage_Capacity']])
Storage_Capacity_dummies_df = pd.DataFrame(Storage_Capacity_dummies, columns=[str(i) for i in sorted(df['Storage_Capacity'].unique())])

In [503]:
df_new = pd.concat([df, Brand_dummies_df, RAM_Size_dummies_df, Storage_Capacity_dummies_df]
                   , axis = 1)

In [504]:
df_new

Brand  Processor_Speed RAM_Size Storage_Capacity  Screen_Size    Weight  \
0      Asus         3.830296       16              512    11.185147  2.641094   
1      Acer         2.912833        4             1000    11.311372  3.260012   
2    Lenovo         3.241627        4              256    11.853023  2.029061   
3      Acer         3.806248       16              512    12.280360  4.573865   
4      Acer         3.268097       32             1000    14.990877  4.193472   
..      ...              ...      ...              ...          ...       ...   
995      HP         3.343584        4             1000    12.587095  3.162399   
996    Dell         2.780555        8              256    12.679356  3.750265   
997    Dell         3.200569        4              512    12.666315  3.392612   
998    Asus         1.604182        8              256    11.215581  3.857613   
999  Lenovo         1.711980        4              256    16.561498  3.440883   

            Price  Brand_new  RAM_Size_new  Storage_Capacity_new  ...  Dell  \
0    17395.093065          1             2                     1  ...   0.0   
1    31607.605919          0             0                     2  ...   0.0   
2     9291.023542          4             0                     0  ...   0.0   
3    17436.728334          0             2                     1  ...   0.0   
4    32917.990718          0             3                     2  ...   0.0   
..            ...        ...           ...                   ...  ...   ...   
995  31593.668017          3             0                     2  ...   0.0   
996   9149.521832          2             1                     0  ...   1.0   
997  16552.404779          2             0                     1  ...   1.0   
998   9407.473459          1             1                     0  ...   0.0   
999   8807.696702          4             0                     0  ...   0.0   

      HP  Lenovo    4    8   16   32  256  512  1000  
0    0.0     0.0  0.0  0.0  1.0  0.0  0.0  1.0   0.0  
1    0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0   1.0  
2    0.0     1.0  1.0  0.0  0.0  0.0  1.0  0.0   0.0  
3    0.0     0.0  0.0  0.0  1.0  0.0  0.0  1.0   0.0  
4    0.0     0.0  0.0  0.0  0.0  1.0  0.0  0.0   1.0  
..   ...     ...  ...  ...  ...  ...  ...  ...   ...  
995  1.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0   1.0  
996  0.0     0.0  0.0  1.0  0.0  0.0  1.0  0.0   0.0  
997  0.0     0.0  1.0  0.0  0.0  0.0  0.0  1.0   0.0  
998  0.0     0.0  0.0  1.0  0.0  0.0  1.0  0.0   0.0  
999  0.0     1.0  1.0  0.0  0.0  0.0  1.0  0.0   0.0  

[1000 rows x 22 columns]

In [505]:
df_new.drop(['Brand', 'RAM_Size', 'Storage_Capacity'], axis=1, inplace = True)

In [506]:
df_new.drop(['Brand_new', 'RAM_Size_new', 'Storage_Capacity_new'], axis = 1, inplace = True)

In [507]:
df = df_new 

In [508]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [509]:
from sklearn.preprocessing import StandardScaler

In [510]:
X = df.drop('Price', axis=1)
y = df['Price']

In [511]:
scaler = StandardScaler()
scaled_X = scaler.fit_transform(X)

In [512]:
X_train, X_test, y_train, y_test = train_test_split(scaled_X, y, test_size=0.2)

In [513]:
X_train

array([[-1.51469467, -1.73712653,  0.66333402, ..., -0.74512412,
        -0.66558354,  1.40577042],
       [-1.38266671,  0.48580368, -1.44082337, ..., -0.74512412,
        -0.66558354,  1.40577042],
       [ 0.52977601,  0.48671077, -1.35218326, ..., -0.74512412,
        -0.66558354,  1.40577042],
       ...,
       [-0.08280406, -0.72129836, -0.00550294, ...,  1.34205829,
        -0.66558354, -0.71135371],
       [-0.89368441,  0.25575714,  1.75818426, ..., -0.74512412,
        -0.66558354,  1.40577042],
       [-1.50382373, -1.05106788,  1.29722196, ..., -0.74512412,
        -0.66558354,  1.40577042]])

In [514]:
model = DecisionTreeRegressor()

model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9989451425992105

In [515]:
from sklearn.metrics import confusion_matrix, classification_report

In [516]:
y_pred = model.predict(X_test) 

In [517]:
print(classification_report(model.predict(scaled_X),y))

ValueError: continuous is not supported